@startuml
title Flujo 2 - Inicio de sesión / Registro de usuario

|#E6E6E6|Usuario|
start
:Accede a la página de inicio de sesión/registro de usuario;

if (¿Ya tiene cuenta?) then (Sí - Iniciar sesión)
  -[#Green,bold]->
  repeat
    -[#Green,bold]->
    :Ingresa credenciales;
    -[#Green,dashed]->

    |#D9F2FF|Módulo de Autenticación|
    :Recibe credenciales;
    -[#Green,bold]->
    :Valida formatos de datos; 
    -[#Green,bold]->

    if (¿Los datos tienen formato válido?) then (No) 

      |Módulo de Autenticación|
      -[#Green,bold]->
      :Informa errores de validación;
      -[#Green,bold]->

    else (Si)
      |#DDF5DD|Gestión de Usuarios|
      -[#Green,dashed]->
      :Busca usuario registrado;
      -[#Green,bold]->
      :Verifica credenciales;
      -[#Green,bold]->

      if (¿Las credenciales son válidas?) then (Sí)
        |Usuario|
        -[#Green,bold]->
        :Visualiza confirmación de inicio de sesión;
        -[#Green,bold]->
        break

      else (No)
        |Gestión de Usuarios|
        -[#Green,bold]->
        :Informa credenciales inválidas;
        -[#Green,bold]->

      endif
    endif

    |Usuario|
    -[#Green,dashed]->
    :Visualiza mensaje de error;
    -[#Green,bold]->

  repeat while (¿Desea reintentar el acceso?) is (Sí) -[#blue,dashed]->

else (No - Registrarse)  
  -[#Red,bold]->
  repeat
    -[#Red,bold]->
    :Ingresa datos de registro;

    |#D9F2FF|Módulo de Autenticación|
    -[#Red]->
    :Recibe datos de registro;
    -[#Red,bold]->
    :Valida formato de datos;
    -[#Red,bold]->
    :Valida coincidencia de contraseñas;
    -[#Red,bold]->

    if (¿Los datos son válidos y las contraseñas coinciden?) then (No)

      |Módulo de Autenticación|
      -[#Red,bold]->
      :Informa errores de validación;
      -[#Red,bold]->
    
    else (Si)
      |#DDF5DD|Gestión de Usuarios|
      -[#Red,bold]->
      :Verifica si el email ya está registrado;
      -[#Red,bold]->

      if (¿El email ya existe?) then (No)
      
        |Gestión de Usuarios|
        -[#Red,bold]->
        :Registra nuevo usuario;
        -[#Red,bold]->

        |Usuario|
        -[#Red,bold]->
        :Visualiza confirmación de registro;
        -[#Red,bold]-> 
        break

      else (Si)
        |Gestión de Usuarios|
        -[#Red,bold]->
        :Informa que el email ya está registrado;
        -[#Red,bold]->
      
      endif
    endif

    |Usuario|
    -[#Red,bold]->
    :Visualiza mensaje de error;
    -[#Red,bold]->

  repeat while (¿Desea reintentar?) is (Sí) -[#blue,dashed]->

endif

|Usuario|
:Retorna al menú principal;

stop
@enduml